# Generated by Django 3.0.5 on 2020-05-03 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_updadte_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='updadte_date',
            new_name='update_date',
        ),
    ]
